# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated manually by mainigautam :-P

PRODUCT_COPY_FILES += \
    vendor/LYF/zx55q05/proprietary/vendor/bin/adsprpcd:$(TARGET_COPY_OUT_VENDOR)/bin/adsprpcd \
    vendor/LYF/zx55q05/proprietary/vendor/bin/btnvtool:$(TARGET_COPY_OUT_VENDOR)/bin/btnvtool \
    vendor/LYF/zx55q05/proprietary/vendor/bin/hci_qcomm_init:$(TARGET_COPY_OUT_VENDOR)/bin/hci_qcomm_init \
    vendor/LYF/zx55q05/proprietary/vendor/bin/irsc_util:$(TARGET_COPY_OUT_VENDOR)/bin/irsc_util \
    vendor/LYF/zx55q05/proprietary/vendor/bin/mm-pp-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-pp-daemon \
    vendor/LYF/zx55q05/proprietary/vendor/bin/mm-qcamera-app:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-app \
    vendor/LYF/zx55q05/proprietary/vendor/bin/mm-qcamera-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qcamera-daemon \
    vendor/LYF/zx55q05/proprietary/vendor/bin/msm_irqbalance:$(TARGET_COPY_OUT_VENDOR)/bin/msm_irqbalance \
    vendor/LYF/zx55q05/proprietary/vendor/bin/netmgrd:$(TARGET_COPY_OUT_VENDOR)/bin/netmgrd \
    vendor/LYF/zx55q05/proprietary/vendor/bin/qmuxd:$(TARGET_COPY_OUT_VENDOR)/bin/qmuxd \
    vendor/LYF/zx55q05/proprietary/vendor/bin/qseecomd:$(TARGET_COPY_OUT_VENDOR)/bin/qseecomd \
    vendor/LYF/zx55q05/proprietary/vendor/bin/radish:$(TARGET_COPY_OUT_VENDOR)/bin/radish \
    vendor/LYF/zx55q05/proprietary/vendor/bin/rmt_storage:$(TARGET_COPY_OUT_VENDOR)/bin/rmt_storage \
    vendor/LYF/zx55q05/proprietary/vendor/bin/time_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/time_daemon \
    vendor/LYF/zx55q05/proprietary/vendor/etc/capability.xml:$(TARGET_COPY_OUT_VENDOR)/etc/capability.xml \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/a225_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pfp.fw \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/a225_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pm4.fw \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/a225p5_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225p5_pm4.fw \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/a300_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pfp.fw \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/a300_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pm4.fw \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/a330_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pfp.fw \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/a330_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pm4.fw \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/a420_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pfp.fw \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/a420_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pm4.fw \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/cyttsp5_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cyttsp5_fw.bin \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/ice40.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ice40.bin \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/venus.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b00 \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/venus.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b01 \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/venus.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b02 \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/venus.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b03 \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/venus.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.b04 \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/venus.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mbn \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/venus.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/venus.mdt \
    vendor/LYF/zx55q05/proprietary/vendor/etc/permissions/com.qti.snapdragon.sdk.display.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.qti.snapdragon.sdk.display.xml \
    vendor/LYF/zx55q05/proprietary/vendor/etc/permissions/qcnvitems.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/qcnvitems.xml \
    vendor/LYF/zx55q05/proprietary/vendor/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/qcrilhook.xml \
    vendor/LYF/zx55q05/proprietary/vendor/framework/com.qti.snapdragon.sdk.display.jar:$(TARGET_COPY_OUT_VENDOR)/framework/com.qti.snapdragon.sdk.display.jar \
    vendor/LYF/zx55q05/proprietary/vendor/lib/hw/camera.msm8916.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.msm8916.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/hw/sensors.msm8916.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.msm8916.so \
		vendor/LYF/zx55q05/proprietary/vendor/lib64/hw/sensors.msm8916.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/sensors.msm8916.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmm-qcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-qcamera.so \
	  vendor/LYF/zx55q05/proprietary/vendor/lib/libcalmodule_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcalmodule_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libcalmodule_vtc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcalmodule_vtc.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libcalmodule_common.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcalmodule_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libcalmodule_vtc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcalmodule_vtc.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_interface.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmjpeg_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg_interface.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmorpho_image_converter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmorpho_image_converter.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmorpho_jpeg_io.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmorpho_jpeg_io.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmorpho_memory_allocator.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmorpho_memory_allocator.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmorpho_strobe_photo_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmorpho_strobe_photo_jni.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libnubia_runtime.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnubia_runtime.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libnubia_servers.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnubia_servers.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libnubia_trajectory.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnubia_trajectory.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libobjectclear.so:$(TARGET_COPY_OUT_VENDOR)/lib/libobjectclear.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libobjectclear_nubia.so:$(TARGET_COPY_OUT_VENDOR)/lib/libobjectclear_nubia.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqomx_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_core.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libskia.so:$(TARGET_COPY_OUT_VENDOR)/lib/libskia.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libskia.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libskia.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libAlgorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libAlgorithm.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libBuffer.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libBuffer.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libFNVfbEngineLib.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libFNVfbEngineLib.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libIndependenceUtil.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libIndependenceUtil.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libNubiaImageAlgorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libNubiaImageAlgorithm.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libNubiaxmptoolkit.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libNubiaxmptoolkit.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libalRnB.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libalRnB.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libalSDE2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libalSDE2.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libavcodec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libavcodec.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libavfilter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libavfilter.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libavformat.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libavformat.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libavutil.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libavutil.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libbuffer_manager.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbuffer_manager.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmorpho_image_converter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmorpho_image_converter.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmorpho_jpeg_io.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmorpho_jpeg_io.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmorpho_memory_allocator.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmorpho_memory_allocator.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmorpho_panorama_gp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmorpho_panorama_gp.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmulti_exposure.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmulti_exposure.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libnubia_clone.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnubia_clone.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libnubia_delay_recorder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnubia_delay_recorder.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libnubia_runtime.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnubia_runtime.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libnubia_servers.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnubia_servers.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libnubia_trajectory.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnubia_trajectory.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libnubiajpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnubiajpeg.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libobjectclear.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libobjectclear.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libobjectclear_nubia.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libobjectclear_nubia.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libpanoramahelper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpanoramahelper.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libproductinfo.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libproductinfo.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/librilqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librilqmiservices.so \
    vendor/LYF/zx55q05/proprietary/vendor/bin/perfd:$(TARGET_COPY_OUT_VENDOR)/bin/perfd \
    vendor/LYF/zx55q05/proprietary/vendor/bin/thermal-engine:$(TARGET_COPY_OUT_VENDOR)/bin/thermal-engine \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/LYF/zx55q05/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/eglSubDriverAndroid.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/egl/eglsubAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/eglsubAndroid.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libEGL_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/egl/libESXEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libESXEGL_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libESXGLESv1_CM_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libESXGLESv2_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv1_CM_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLESv2_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/egl/libQTapGLES.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libQTapGLES.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/egl/libRBEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libRBEGL_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libRBGLESv1_CM_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libRBGLESv2_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/hw/flp.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/flp.default.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libC2D2.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib/libCB.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libDivxDrm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libDivxDrm.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libFlacSwDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libFlacSwDec.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libI420colorconvert.so:$(TARGET_COPY_OUT_VENDOR)/lib/libI420colorconvert.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libOmxAacDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxAacDec.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libOmxAmrwbplusDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxAmrwbplusDec.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libOmxEvrcDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxEvrcDec.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libOmxMux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxMux.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libOmxQcelp13Dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxQcelp13Dec.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libOmxWmaDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxWmaDec.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCL.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libQSEEComAPI.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/libRSDriver_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libSHIMDivxDrm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSHIMDivxDrm.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libTimeService.so:$(TARGET_COPY_OUT_VENDOR)/lib/libTimeService.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libacdb-fts.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdb-fts.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbloader.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libacdbmapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbmapper.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libacdbrtac.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdbrtac.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libadiertac.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadiertac.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadreno_utils.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libadsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libadsprpc.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudcal.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libaudioalsa.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudioalsa.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libc2d30-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30-a3xx.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libc2d30-a4xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2d30-a4xx.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libcalmodule_gyroscope.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcalmodule_gyroscope.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiag.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsi_netctrl.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsutils.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libfastcvopt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfastcvopt.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgsl.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libhwdaphal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhwdaphal.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libidl.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libjpegdhw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdhw.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libjpegehw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegehw.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libllvm-glnext.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-glnext.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-qcom.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdmdetect.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmm-color-convertor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-color-convertor.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmQSM.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmQSM.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera2_c2d_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_c2d_module.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera2_cpp_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_cpp_module.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_frame_algorithm.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_iface_modules.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_imglib_modules.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera2_is.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_is.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_isp_modules.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pproc_modules.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera2_q3a_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_q3a_core.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_algorithm.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_modules.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera2_vpe_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_vpe_module.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera2_wnr_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_wnr_module.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_faceproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_faceproc.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_gb_lib.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_hdr_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_lib.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_hi256.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hi256.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_imglib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_tintless_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_algo.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_wavelet_lib.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmipl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmipl.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmparser.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmparser.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmqjpeg_codec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpeg_codec.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/liboemcrypto.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcrypto.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqcci_legacy.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdi.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqdp.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_cci.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqmi_client_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_helper.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_qmux.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_common_so.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csi.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_encdec.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmiservices.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqomx_jpegdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegdec.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqomx_jpegenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqti-iop-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqti-iop-client.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqti-perfd-client.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib/librs_adreno_sha1.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libsc-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsc-a3xx.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libscale.so:$(TARGET_COPY_OUT_VENDOR)/lib/libscale.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libsmemlog.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsmemlog.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libstlport.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstlport.so \
		vendor/LYF/zx55q05/proprietary/vendor/etc/calmodule.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/calmodule.cfg  \
	  vendor/LYF/zx55q05/proprietary/vendor/lib64/libstlport.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libstlport.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libthermalclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libthermalclient.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libvoice-svc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvoice-svc.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib/libxml.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/qcdrm/playready/lib/drm/libdrmprplugin_customer.so:$(TARGET_COPY_OUT_VENDOR)/lib/qcdrm/playready/lib/drm/libdrmprplugin_customer.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/qcdrm/playready/lib/libprdrmdecrypt_customer.so:$(TARGET_COPY_OUT_VENDOR)/lib/qcdrm/playready/lib/libprdrmdecrypt_customer.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/qcdrm/playready/lib/libtzplayready_customer.so:$(TARGET_COPY_OUT_VENDOR)/lib/qcdrm/playready/lib/libtzplayready_customer.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/qcdrm/playready/lib/mediadrm/libprmediadrmdecrypt_customer.so:$(TARGET_COPY_OUT_VENDOR)/lib/qcdrm/playready/lib/mediadrm/libprmediadrmdecrypt_customer.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/qcdrm/playready/lib/mediadrm/libprmediadrmplugin_customer.so:$(TARGET_COPY_OUT_VENDOR)/lib/qcdrm/playready/lib/mediadrm/libprmediadrmplugin_customer.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/soundfx/libqcbassboost.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libqcbassboost.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/soundfx/libqcreverb.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libqcreverb.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/soundfx/libqcvirt.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libqcvirt.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/egl/eglSubDriverAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/eglSubDriverAndroid.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/egl/eglsubAndroid.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/eglsubAndroid.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/egl/libEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libEGL_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/egl/libESXEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libESXEGL_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/egl/libESXGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libESXGLESv1_CM_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/egl/libESXGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libESXGLESv2_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/egl/libGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv1_CM_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/egl/libGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLESv2_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/egl/libQTapGLES.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libQTapGLES.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/egl/libRBEGL_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libRBEGL_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/egl/libRBGLESv1_CM_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libRBGLESv1_CM_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/egl/libRBGLESv2_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libRBGLESv2_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/egl/libq3dtools_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libq3dtools_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/hw/flp.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/flp.default.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/lib-sec-disp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib-sec-disp.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libC2D2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libC2D2.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libCB.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libCB.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libDivxDrm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libDivxDrm.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libFlacSwDec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libFlacSwDec.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libOmxAacDec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libOmxAacDec.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libOmxMux.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libOmxMux.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libOpenCL.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libQSEEComAPI.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libQSEEComAPI.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libRSDriver_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libRSDriver_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libSHIMDivxDrm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libSHIMDivxDrm.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libSecureUILib.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libSecureUILib.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libStDrvInt.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libStDrvInt.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libTimeService.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libTimeService.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libacdb-fts.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdb-fts.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libacdbloader.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbloader.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libacdbmapper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbmapper.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libacdbrtac.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdbrtac.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libadiertac.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadiertac.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libadreno_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadreno_utils.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libadsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libadsprpc.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libaudcal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudcal.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libaudioalsa.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudioalsa.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libbtnv.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbtnv.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libc2d30-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libc2d30-a3xx.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libc2d30-a4xx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libc2d30-a4xx.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libcalmodule_gyroscope.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcalmodule_gyroscope.so \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw  \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw  \
    vendor/LYF/zx55q05/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/lib-imscamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-imscamera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libOmxVdecHevc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOmxVdecHevc.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_bu64297_q13v06k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_bu64297_q13v06k.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_bu64297_q13v06k_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_bu64297_q13v06k_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_bu64297_q13v06k_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_bu64297_q13v06k_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9714.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9714_13p1ba_h2x.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714_13p1ba_h2x.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9714_13p1ba_h2x_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714_13p1ba_h2x_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9714_13p1ba_h2x_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714_13p1ba_h2x_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9714_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9714_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9714_meituosi_h2x.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714_meituosi_h2x.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9714_meituosi_h2x_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714_meituosi_h2x_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9714_meituosi_h2x_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714_meituosi_h2x_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9714_sikao_h2x.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714_sikao_h2x.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9714_sikao_h2x_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714_sikao_h2x_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9714_sikao_h2x_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9714_sikao_h2x_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9718s.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9718s.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9718s_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9718s_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9718s_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9718s_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9718s_sunny_a11.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9718s_sunny_a11.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9718s_sunny_a11_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9718s_sunny_a11_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9718s_sunny_a11_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9718s_sunny_a11_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9761b.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9761b.so   \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9761b_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9761b_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9761b_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9761b_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9761b_ov13853.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9761b_ov13853.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9761b_ov13853_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9761b_ov13853_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_dw9761b_ov13853_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9761b_ov13853_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_rohm_bu64243gwz.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64243gwz.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_a11.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64243gwz_a11.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_a11_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64243gwz_a11_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_a11_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64243gwz_a11_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64243gwz_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64243gwz_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_h2x.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64243gwz_h2x.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_h2x_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64243gwz_h2x_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_rohm_bu64243gwz_h2x_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64243gwz_h2x_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_rohm_bu64244.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64244.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_rohm_bu64244_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64244_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libactuator_rohm_bu64244_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_rohm_bu64244_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libavcodec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libavcodec.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libavformat.so:$(TARGET_COPY_OUT_VENDOR)/lib/libavformat.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libcamerahandler_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcamerahandler_jni.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_gc2355_8916_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_gc2355_8916_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_gc2355_8916_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_gc2355_8916_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_gc2355_8916_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_gc2355_8916_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_imx219_q8n13a_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_q8n13a_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_imx219_q8n13a_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_q8n13a_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_imx219_q8n13a_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_q8n13a_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_imx219_q8n13a_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_q8n13a_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_imx219_q8n13a_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_q8n13a_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov13850_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13850_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov13850_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13850_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov13850_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13850_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov13850_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13850_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov13850_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13850_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov13850_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13850_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov13850_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13850_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov13853_q13853a_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13853_q13853a_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov13853_q13853a_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13853_q13853a_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov13853_q13853a_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13853_q13853a_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov13853_q13853a_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13853_q13853a_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov13853_q13853a_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13853_q13853a_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov13853_q13853a_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13853_q13853a_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov13853_q13853a_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov13853_q13853a_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2680_5987fhq_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2680_5987fhq_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2680_5987fhq_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov2680_5987fhq_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2680_5987fhq_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov2680_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2680_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov2680_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2680_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov2680_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2680_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov2680_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov2680_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_86001_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_86001_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_86001_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_86001_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_86001_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_86001_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_86001_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_86001_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_86001_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_86001_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_86001_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_86001_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_86001_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_86001_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_86001_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_86001_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_86001_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_86001_video_hd.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_86001_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_86001_zsl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_sunny_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_sunny_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_sunny_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_sunny_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_sunny_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_sunny_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_sunny_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_sunny_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_sunny_video_hd.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_sunny_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_sunny_zsl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_video_hd.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_a11_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_a11_zsl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_common.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_lenplus_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_lenplus_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_lenplus_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_lenplus_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_lenplus_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_lenplus_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_lenplus_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_lenplus_video_hd.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_lenplus_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_lenplus_zsl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_nubiacust.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_nubiacust.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_preview.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_qtech_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_qtech_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_qtech_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_qtech_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_qtech_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_qtech_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_qtech_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_qtech_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_qtech_video_hd.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_qtech_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_qtech_zsl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_sunny_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_sunny_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_sunny_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_sunny_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_sunny_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_sunny_liveshot.so   \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_sunny_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_sunny_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_sunny_video_hd.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_sunny_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_sunny_zsl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_video_hd.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov5670_q5v41b_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov5670_q5v41b_zsl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8858_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8858_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8858_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8858_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8858_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8858_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8858_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8858_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8858_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8858_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8858_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8858_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8858_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8858_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8858_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8858_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_sunny_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_sunny_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_sunny_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_sunny_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_sunny_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_sunny_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_sunny_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_sunny_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_sunny_video_hd.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_sunny_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_sunny_zsl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_video_hd.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_a11_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_a11_zsl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_q8v18a_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_q8v18a_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_q8v18a_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_q8v18a_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_q8v18a_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_q8v18a_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_q8v18a_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_q8v18a_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_q8v18a_video_hd.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_q8v18a_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_q8v18a_zsl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_qtech_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_qtech_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_qtech_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_qtech_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_qtech_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_qtech_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_qtech_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_qtech_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_qtech_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_qtech_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_qtech_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_qtech_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_qtech_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_qtech_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_qtech_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_qtech_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_qtech_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_qtech_video_hd.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_qtech_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_qtech_zsl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_sunny_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_sunny_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_sunny_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_sunny_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_sunny_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_sunny_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_sunny_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_sunny_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_sunny_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_sunny_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_sunny_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_sunny_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_sunny_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_sunny_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_sunny_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_sunny_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_sunny_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_sunny_video_hd.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_ov8865_sunny_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_ov8865_sunny_zsl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3h7_8916_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7_8916_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3h7_8916_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7_8916_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3h7_8916_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7_8916_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3h7_8916_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3h7_8916_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l2_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l2_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l2_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l2_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l2_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l2_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l2_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l2_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l2_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l2_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l2_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l2_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l2_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l2_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l2_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l2_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l2_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l2_video_hd.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l2_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l2_zsl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_qtech_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_qtech_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_qtech_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_qtech_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_qtech_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_qtech_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_qtech_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_qtech_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_qtech_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_qtech_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_qtech_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_qtech_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_qtech_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_qtech_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_sunny_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_sunny_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_sunny_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_sunny_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_sunny_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_sunny_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_sunny_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_sunny_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_sunny_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_sunny_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_sunny_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_sunny_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k3l8_sunny_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l8_sunny_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k5e8_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k5e8_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k5e8_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k5e8_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k5e8_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k5e8_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k5e8_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k5e8_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k5e8_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_video_hd.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_s5k5e8_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e8_zsl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_sp2508_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sp2508_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_sp2508_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sp2508_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_sp2508_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sp2508_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_sp2508_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_sp2508_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_t4kb3_mcnex_res0_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_t4kb3_mcnex_res0_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_t4kb3_mcnex_res0_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_t4kb3_mcnex_res0_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_t4kb3_mcnex_res1_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_t4kb3_mcnex_res1_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_t4kb3_mcnex_res1_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_t4kb3_mcnex_res1_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_t4kb3_mcnex_res2_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_t4kb3_mcnex_res2_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_t4kb3_mcnex_res2_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_t4kb3_mcnex_res2_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_t4kb3_mcnex_res3_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_t4kb3_mcnex_res3_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_t4kb3_mcnex_res3_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_t4kb3_mcnex_res3_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_t4kb3_mcnex_res4_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_t4kb3_mcnex_res4_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_t4kb3_mcnex_res4_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_t4kb3_mcnex_res4_snapshot.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_t4kb3_mcnex_res5_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_t4kb3_mcnex_res5_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_t4kb3_mcnex_res5_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_t4kb3_mcnex_res5_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_t4kb3_mcnex_res6_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_t4kb3_mcnex_res6_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libchromatix_t4kb3_mcnex_res6_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_t4kb3_mcnex_res6_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libffmpeg_extractor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libffmpeg_extractor.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libffmpeg_omx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libffmpeg_omx.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libffmpeg_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libffmpeg_utils.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libimscamera_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimscamera_jni.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/liblowi_client.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblowi_client.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/liblqe.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblqe.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmm-abl-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-abl-oem.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmm-abl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-abl.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmm-als.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-als.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmm-disp-apis.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-disp-apis.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmm-hdcpmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-hdcpmgr.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmm-omxcore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-omxcore.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmm-qdcm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmm-qdcm.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_gc2355_8916.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_gc2355_8916.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_imx219_q8n13a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx219_q8n13a.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_mt9m114.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_mt9m114.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_nubiacustpro.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_nubiacustpro.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_ov13850.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov13850.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_ov13850_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov13850_eeprom.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_ov13853_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov13853_eeprom.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_ov13853_q13853a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov13853_q13853a.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_ov2680.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov2680.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_ov2680_5987fhq.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov2680_5987fhq.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_ov2680_skuhf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov2680_skuhf.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_ov5670_86001.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov5670_86001.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_ov5670_q5v41b.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov5670_q5v41b.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_ov5670_q5v41b_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov5670_q5v41b_eeprom.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_ov8858.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov8858.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_ov8865_a11.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov8865_a11.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_ov8865_a11_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov8865_a11_eeprom.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_ov8865_q8v18a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_ov8865_q8v18a.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_pdaf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdaf.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_pdafcamif.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdafcamif.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_s5k3h7_8916.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3h7_8916.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_s5k3h7_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3h7_eeprom.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_s5k3l2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3l2.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_s5k3l8.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3l8.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_s5k3l8_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3l8_eeprom.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_s5k5e8.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k5e8.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_s5k5e8_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k5e8_eeprom.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_sp2508.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sp2508.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_sunny_ov8858_q8v19w_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sunny_ov8858_q8v19w_eeprom.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_sunny_q8v18a_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sunny_q8v18a_eeprom.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_t4kb3_mcnex.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_t4kb3_mcnex.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_t4kb3_mcnex_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_t4kb3_mcnex_eeprom.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_t4kb3_qtech.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_t4kb3_qtech.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_t4kb3_qtech_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_t4kb3_qtech_eeprom.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libmmcamera_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tuning.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libOmxVdecHevc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libOmxVdecHevc.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libactuator_dw9718s.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libactuator_dw9718s.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libactuator_dw9718s_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libactuator_dw9718s_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libactuator_dw9718s_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libactuator_dw9718s_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libactuator_dw9718s_sunny_a11_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libactuator_dw9718s_sunny_a11_camcorder.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libactuator_dw9718s_sunny_a11_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libactuator_dw9718s_sunny_a11_camera.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_gc2355_8916_common.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_gc2355_8916_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_gc2355_8916_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_gc2355_8916_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_gc2355_8916_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_gc2355_8916_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_imx219_q8n13a_common.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx219_q8n13a_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_imx219_q8n13a_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx219_q8n13a_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_imx219_q8n13a_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx219_q8n13a_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_imx219_q8n13a_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx219_q8n13a_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_imx219_q8n13a_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_imx219_q8n13a_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_ov13850_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_ov13850_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_ov13853_q13853a_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_ov13853_q13853a_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_ov8858_common.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_ov8858_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_ov8858_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_ov8858_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_ov8858_hfr_120fps.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_ov8858_hfr_120fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_ov8858_hfr_60fps.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_ov8858_hfr_60fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_ov8858_hfr_90fps.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_ov8858_hfr_90fps.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_ov8858_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_ov8858_liveshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_ov8858_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_ov8858_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_ov8858_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_ov8858_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_sp2508_common.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_sp2508_common.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_sp2508_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_sp2508_default_video.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_sp2508_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_sp2508_preview.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libchromatix_sp2508_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libchromatix_sp2508_snapshot.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmm-omxcore.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-omxcore.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmmcamera2_q3a_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera2_q3a_core.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmmcamera_gc2355_8916.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera_gc2355_8916.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmmcamera_imx219_q8n13a.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera_imx219_q8n13a.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmmcamera_ov8858.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera_ov8858.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmmcamera_sp2508.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera_sp2508.so  \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libconfigdb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libconfigdb.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdiag.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libdisp-aba.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdisp-aba.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libdrmfs.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmfs.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libdrmtime.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmtime.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libdsi_netctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsi_netctrl.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdsutils.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libgsl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgsl.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libhwdaphal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhwdaphal.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libidl.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libllvm-glnext.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-glnext.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libllvm-qcom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-qcom.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/liblqe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblqe.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmdmdetect.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmdmdetect.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmm-abl-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-abl-oem.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmm-abl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-abl.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmm-als.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-als.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmm-disp-apis.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-disp-apis.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmm-hdcpmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-hdcpmgr.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmm-qdcm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmm-qdcm.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmmcamera2_frame_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera2_frame_algorithm.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmcamera2_stats_algorithm.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libmmparser.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmparser.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libnetmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnetmgr.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libperipheral_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libperipheral_client.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqcci_legacy.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libqdi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdi.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libqdp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqdp.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_cci.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libqmi_client_helper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_client_helper.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_client_qmux.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_common_so.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_csi.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmi_encdec.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqmiservices.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libqti-iop-client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqti-iop-client.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libqti-perfd-client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libqti-perfd-client.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libril-qc-ltedirectdisc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-ltedirectdisc.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libril-qc-qmi-1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-qmi-1.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libril-qc-radioconfig.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-radioconfig.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libril-qcril-hook-oem.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libril-qcril-hook-oem.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/librpmb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librpmb.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/librs_adreno.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librs_adreno.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/librs_adreno_sha1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librs_adreno_sha1.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libsc-a3xx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsc-a3xx.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libscale.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libscale.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libsecureui.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsecureui.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libsecureui_svcsock.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsecureui_svcsock.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libsettings.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsettings.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libsmemlog.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsmemlog.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libssd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libssd.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libsystem_health_mon.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsystem_health_mon.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libthermalclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libthermalclient.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libthermalioctl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libthermalioctl.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libvoice-svc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvoice-svc.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libxml.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libxml.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib64/mediadrm/libwvdrmengine.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/qcdrm/playready/lib/libtzplayready_customer.so:$(TARGET_COPY_OUT_VENDOR)/lib64/qcdrm/playready/lib/libtzplayready_customer.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/qcdrm/playready/lib/mediadrm/libprmediadrmplugin_customer.so:$(TARGET_COPY_OUT_VENDOR)/lib64/qcdrm/playready/lib/mediadrm/libprmediadrmplugin_customer.so  \
    vendor/LYF/zx55q05/proprietary/vendor/bin/mm-qjpeg-dec-test:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qjpeg-dec-test  \
    vendor/LYF/zx55q05/proprietary/vendor/bin/mm-qjpeg-enc-test:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qjpeg-enc-test  \
    vendor/LYF/zx55q05/proprietary/vendor/bin/mm-qomx-idec-test:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qomx-idec-test  \
    vendor/LYF/zx55q05/proprietary/vendor/bin/mm-vidc-omx-test:$(TARGET_COPY_OUT_VENDOR)/bin/mm-vidc-omx-test  \
    vendor/LYF/zx55q05/proprietary/vendor/bin/mm-qomx-ienc-test:$(TARGET_COPY_OUT_VENDOR)/bin/mm-qomx-ienc-test  \

# GPS-blobs (kang from xiaomi_msm8953-common)
PRODUCT_COPY_FILES += \
    vendor/LYF/zx55q05/proprietary/vendor/bin/hw/vendor.qti.gnss@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.qti.gnss@1.0-service \
    vendor/LYF/zx55q05/proprietary/vendor/etc/init/vendor.qti.gnss@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.gnss@1.0-service.rc \
    vendor/LYF/zx55q05/proprietary/vendor/bin/loc_launcher:$(TARGET_COPY_OUT_VENDOR)/bin/loc_launcher \
    vendor/LYF/zx55q05/proprietary/vendor/bin/lowi-server:$(TARGET_COPY_OUT_VENDOR)/bin/lowi-server \
    vendor/LYF/zx55q05/proprietary/vendor/bin/slim_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/slim_daemon \
    vendor/LYF/zx55q05/proprietary/vendor/bin/xtra-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/xtra-daemon \
    vendor/LYF/zx55q05/proprietary/vendor/etc/cacert_location.pem:$(TARGET_COPY_OUT_VENDOR)/etc/cacert_location.pem \
    vendor/LYF/zx55q05/proprietary/vendor/etc/xtra_root_cert.pem:$(TARGET_COPY_OUT_VENDOR)/etc/xtra_root_cert.pem \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/hw/vendor.qti.gnss@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/vendor.qti.gnss@1.0-impl.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libalarmservice_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libalarmservice_jni.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libdataitems.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdataitems.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libdrplugin_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrplugin_client.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libDRPlugin.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libDRPlugin.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libevent_observer.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libevent_observer.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libflp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libflp.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libgdtap.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgdtap.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libgeofence.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgeofence.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libizat_client_api.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libizat_client_api.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libizat_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libizat_core.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/liblbs_core.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblbs_core.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libloc_ds_api.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libloc_ds_api.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libloc_externalDr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libloc_externalDr.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/liblocationservice_glue.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblocationservice_glue.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/liblocationservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblocationservice.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/liblowi_client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblowi_client.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/liblowi_wifihal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/liblowi_wifihal.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libquipc_os_api.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libquipc_os_api.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libsensor1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsensor1.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libulp2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libulp2.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libxtadapter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libxtadapter.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libxtwifi_ulp_adaptor.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libxtwifi_ulp_adaptor.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/vendor.qti.gnss@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.gnss@1.0.so

# ANT-blobs (kang from xiaomi_msm8953-common)
PRODUCT_COPY_FILES += \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/com.qualcomm.qti.ant@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.qualcomm.qti.ant@1.0.so

# QTI BT blobs (kang from xiaomi_msm8953-common)
PRODUCT_COPY_FILES += \
    vendor/LYF/zx55q05/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/LYF/zx55q05/proprietary/vendor/bin/hw/android.hardware.bluetooth@1.0-service-qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.bluetooth@1.0-service-qti \
    vendor/LYF/zx55q05/proprietary/vendor/bin/wcnss_filter:$(TARGET_COPY_OUT_VENDOR)/bin/wcnss_filter \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/hw/android.hardware.bluetooth@1.0-impl-qti.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/android.hardware.bluetooth@1.0-impl-qti.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libbt-hidlclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbt-hidlclient.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/vendor.qti.hardware.fm@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.fm@1.0.so

# More shared Vulkan blobs
PRODUCT_COPY_FILES += \
    vendor/LYF/zx55q05/proprietary/vendor/lib/egl/libq3dtools_esx.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libq3dtools_esx.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/egl/libq3dtools_esx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libq3dtools_esx.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/hw/vulkan.msm8916.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vulkan.msm8916.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/hw/vulkan.msm8916.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/vulkan.msm8916.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbccQTI.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libbccQTI.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbccQTI.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib/libllvm-qgl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libllvm-qgl.so \
    vendor/LYF/zx55q05/proprietary/vendor/lib64/libllvm-qgl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libllvm-qgl.so


PRODUCT_PACKAGES += \
    libloc_api_v02 \
    libtime_genoff \
    TimeService \
    colorservice \
    shutdownlistener \
    qcrilmsgtunnel \
    qcnvitems \
    qcrilhook
